version: '1.0.0'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/code:ro
    environment:
      - DATABASE_URL=postgresql://postgres:Bright#1270@localhost:5433/dockert
    restart: always
    ports:
      - "8000:80"
    networks:
      - currency-converter

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bright#1270
      - POSTGRES_DB=dockert

volumes:
  postgres_data:

networks:
  currency-converter: