version: '3.8'

services:
  api-service:
    container_name: currency-converter-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/code:ro
      - ./.pytest_cache:/code/.pytest_cache
    environment:
      DATABASE_URL: ${DATABASE_URL}
      CB_API_KEY: ${CB_API_KEY}
    restart: always
    command: bash -c 'while !</dev/tcp/db/5433; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --host 0.0.0.0'
    ports:
      - 8080:8000

  db:
    image: postgres:15-alpine
    volumes:
      - psql_data:/var/lib/postgresql/data/
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: -p 5433

volumes:
  psql_data:
