version: '3.8'

services:
  api-service:
    container_name: currency-conveter-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/code:ro
      - ./.pytest_cache:/code/.pytest_cache
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:Bright#1270@db:5433/exchange_rate
    restart: always
    command: bash -c 'alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --reload'
    ports:
      - 8080:8000

  db:
    image: postgres:15-alpine
    volumes:
      - psql_data:/var/lib/postgresql/data/
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Bright#1270
      - POSTGRES_DB=exchange_rate
    command: -p 5433

volumes:
  psql_data:
