name: API CI-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run tests
      - name: Docker Compose remove old containers and volumes
        run: docker-compose down -v --remove-orphans
      - name: Docker Compose up
        run: docker-compose up -d --build
      - name: Lint with flake8
        run: |
          docker-compose exec api-service flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          docker-compose exec api-service flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Docker Compose run tests
        run: docker-compose exec api-service pytest -v
      - name: Generate coverage report
        run: |
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
      - name: Docker Compose cleanup
        run: docker-compose down -v --remove-orphans
