name: API CI-test-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CB_API_KEY: ${{ secrets.CB_API_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run tests
        run: docker compose build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CB_API_KEY: ${{ secrets.CB_API_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      - name: Docker Compose remove old containers and volumes
        run: docker compose down -v --remove-orphans
      - name: Print environment variable
        run: echo ${{ secrets.DATABASE_URL }}
      - name: Docker Compose up
        run: docker compose up -d
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CB_API_KEY: ${{ secrets.CB_API_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      - name: Current working dir
        run: pwd
      - name: Container details
        run: docker logs currency-converter-api
      - name: Docker Compose run tests
        run: docker compose exec -T currency-converter-api pytest -v
      - name: Docker Compose cleanup
        run: docker compose down -v --remove-orphans
